.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. hycoin_qt test_hycoin_qt
clean: FORCE
	$(MAKE) -C .. hycoin_qt_clean test_hycoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_hycoin_qt_check
hycoin-qt hycoin-qt.exe: FORCE
	 $(MAKE) -C .. hycoin_qt
